FROM google/dart:2.2
COPY ./ ./
# Install dependencies, pre-build
RUN pub get
# Generate snapshot
RUN dart --snapshot=bin/prod.snapshot  bin/prod.dart
# Set environment, start server
ENV ANGEL_ENV=production
EXPOSE 3000
CMD dart bin/prod.snapshot